"""
Comprehensive solvent dictionaries mapping name variants to canonical SMILES.

SOLVENT_DICT: 350+ reaction/workup/purification solvent name variants.
DEUTERATED_SOLVENTS: Deuterated NMR solvents (always classified as analytical).

All entries are lowercase keys mapped to canonical SMILES strings.
Matching is done longest-first to ensure specificity (e.g., "ethyl acetate"
matches before "acetate").
"""

SOLVENT_DICT = {
    # ===== WATER =====
    "water": "O",
    "h2o": "O",
    "brine": "O",
    "aqueous": "O",
    "sat. aq.": "O",
    "saturated aqueous": "O",

    # ===== CARBOXYLIC ACIDS =====
    "lactic acid": "CC(O)C(=O)O",
    "2-hydroxypropanoic acid": "CC(O)C(=O)O",
    "propionic acid": "CCC(=O)O",
    "propanoic acid": "CCC(=O)O",
    "methanesulfonic acid": "CS(=O)(=O)O",
    "msa": "CS(=O)(=O)O",
    "mesylic acid": "CS(=O)(=O)O",
    "formic acid": "O=CO",
    "hcooh": "O=CO",
    "methanoic acid": "O=CO",
    "acetic acid": "CC(=O)O",
    "hoac": "CC(=O)O",
    "glacial acetic acid": "CC(=O)O",
    "acoh": "CC(=O)O",
    "ethanoic acid": "CC(=O)O",
    "aca": "CC(=O)O",
    "trifluoroacetic acid": "FC(F)(F)C(=O)O",
    "tfa": "FC(F)(F)C(=O)O",
    "tfaa": "FC(F)(F)C(=O)O",
    "trichloroacetic acid": "O=C(O)C(Cl)(Cl)Cl",
    "tca": "O=C(O)C(Cl)(Cl)Cl",

    # ===== ALCOHOLS - DIOLS/POLYOLS =====
    "1,3-propanediol": "OCCCO",
    "propane-1,3-diol": "OCCCO",
    "trimethylene glycol": "OCCCO",
    "1,3-pdo": "OCCCO",
    "ethylene glycol": "OCCO",
    "1,2-ethanediol": "OCCO",
    "ethane-1,2-diol": "OCCO",
    "meg": "OCCO",
    "eg": "OCCO",
    "diethylene glycol": "OCCOCCO",
    "di(ethylene glycol)": "OCCOCCO",
    "deg": "OCCOCCO",
    "2,2'-oxydiethanol": "OCCOCCO",
    "triethylene glycol": "OCCOCCOCCO",
    "tri(ethylene glycol)": "OCCOCCOCCO",
    "teg": "OCCOCCOCCO",
    "1,2-propanediol": "CC(O)CO",
    "propylene glycol": "CC(O)CO",
    "propane-1,2-diol": "CC(O)CO",
    "mpg": "CC(O)CO",
    "glycerol": "OCC(O)CO",
    "glycerin": "OCC(O)CO",
    "glycerine": "OCC(O)CO",
    "1,2,3-propanetriol": "OCC(O)CO",
    "1,4-butanediol": "OCCCCO",
    "butane-1,4-diol": "OCCCCO",
    "1,4-bdo": "OCCCCO",
    "tetramethylene glycol": "OCCCCO",
    "1,2-isopropylidene glycerol": "CC1(C)OCC(CO)O1",
    "solketal": "CC1(C)OCC(CO)O1",
    "2,2-dimethyl-1,3-dioxolane-4-methanol": "CC1(C)OCC(CO)O1",

    # ===== ALCOHOLS - PRIMARY =====
    "methanol": "CO",
    "meoh": "CO",
    "methyl alcohol": "CO",
    "ch3oh": "CO",
    "wood alcohol": "CO",
    "ethanol": "CCO",
    "etoh": "CCO",
    "ethyl alcohol": "CCO",
    "c2h5oh": "CCO",
    "alcohol": "CCO",
    "grain alcohol": "CCO",
    "1-propanol": "CCCO",
    "n-propanol": "CCCO",
    "propan-1-ol": "CCCO",
    "n-proh": "CCCO",
    "propyl alcohol": "CCCO",
    "1-butanol": "CCCCO",
    "n-butanol": "CCCCO",
    "butan-1-ol": "CCCCO",
    "butanol": "CCCCO",
    "n-buoh": "CCCCO",
    "butyl alcohol": "CCCCO",
    "1-pentanol": "CCCCCO",
    "n-pentanol": "CCCCCO",
    "pentan-1-ol": "CCCCCO",
    "amyl alcohol": "CCCCCO",
    "pentyl alcohol": "CCCCCO",
    "1-hexanol": "CCCCCCO",
    "n-hexanol": "CCCCCCO",
    "hexan-1-ol": "CCCCCCO",
    "hexyl alcohol": "CCCCCCO",
    "1-heptanol": "CCCCCCCO",
    "n-heptanol": "CCCCCCCO",
    "heptan-1-ol": "CCCCCCCO",
    "heptyl alcohol": "CCCCCCCO",
    "1-octanol": "CCCCCCCCO",
    "n-octanol": "CCCCCCCCO",
    "octan-1-ol": "CCCCCCCCO",
    "octyl alcohol": "CCCCCCCCO",
    "capryl alcohol": "CCCCCCCCO",
    "2-ethylhexanol": "CCCCC(CC)CO",
    "2-ethyl hexanol": "CCCCC(CC)CO",
    "2-ethyl-1-hexanol": "CCCCC(CC)CO",
    "2-ethylhexan-1-ol": "CCCCC(CC)CO",
    "isooctyl alcohol": "CCCCC(CC)CO",
    "benzyl alcohol": "OCc1ccccc1",
    "phenylmethanol": "OCc1ccccc1",
    "benzenemethanol": "OCc1ccccc1",
    "bnoh": "OCc1ccccc1",
    "phenyl carbinol": "OCc1ccccc1",
    "tetrahydrofurfuryl alcohol": "OCC1CCCO1",
    "thfa": "OCC1CCCO1",
    "tetrahydro-2-furanmethanol": "OCC1CCCO1",
    "2-methoxyethanol": "COCCO",
    "methyl cellosolve": "COCCO",
    "ethylene glycol monomethyl ether": "COCCO",
    "egme": "COCCO",

    # ===== ALCOHOLS - SECONDARY =====
    "2-propanol": "CC(C)O",
    "isopropanol": "CC(C)O",
    "isopropyl alcohol": "CC(C)O",
    "ipa": "CC(C)O",
    "propan-2-ol": "CC(C)O",
    "i-proh": "CC(C)O",
    "iproh": "CC(C)O",
    "iso-propanol": "CC(C)O",
    "rubbing alcohol": "CC(C)O",
    "2-butanol": "CCC(C)O",
    "sec-butanol": "CCC(C)O",
    "butan-2-ol": "CCC(C)O",
    "s-buoh": "CCC(C)O",
    "sec-butyl alcohol": "CCC(C)O",
    "2-pentanol": "CCCC(C)O",
    "pentan-2-ol": "CCCC(C)O",
    "sec-amyl alcohol": "CCCC(C)O",
    "cyclohexanol": "OC1CCCCC1",
    "hexahydrophenol": "OC1CCCCC1",
    "cyclohexyl alcohol": "OC1CCCCC1",

    # ===== ALCOHOLS - TERTIARY =====
    "t-butanol": "CC(C)(C)O",
    "tert-butanol": "CC(C)(C)O",
    "t-buoh": "CC(C)(C)O",
    "tert-butyl alcohol": "CC(C)(C)O",
    "2-methyl-2-propanol": "CC(C)(C)O",
    "2-methylpropan-2-ol": "CC(C)(C)O",
    "tba": "CC(C)(C)O",
    "t-amyl alcohol": "CCC(C)(C)O",
    "tert-amyl alcohol": "CCC(C)(C)O",
    "2-methyl-2-butanol": "CCC(C)(C)O",
    "2-methylbutan-2-ol": "CCC(C)(C)O",
    "tert-pentanol": "CCC(C)(C)O",
    "taa": "CCC(C)(C)O",
    "amylene hydrate": "CCC(C)(C)O",

    # ===== ALCOHOLS - BRANCHED =====
    "isobutanol": "CC(C)CO",
    "isobutyl alcohol": "CC(C)CO",
    "2-methylpropan-1-ol": "CC(C)CO",
    "2-methyl-1-propanol": "CC(C)CO",
    "i-buoh": "CC(C)CO",
    "isoamyl alcohol": "CC(C)CCO",
    "isopentyl alcohol": "CC(C)CCO",
    "3-methylbutan-1-ol": "CC(C)CCO",
    "3-methyl-1-butanol": "CC(C)CCO",
    "isopentanol": "CC(C)CCO",

    # ===== ALCOHOLS - FLUORINATED =====
    "2,2,2-trifluoroethanol": "OCC(F)(F)F",
    "tfe": "OCC(F)(F)F",
    "trifluoroethanol": "OCC(F)(F)F",
    "tfea": "OCC(F)(F)F",

    # ===== ESTERS - ACETATES =====
    "methyl acetate": "COC(C)=O",
    "meaoac": "COC(C)=O",
    "meoac": "COC(C)=O",
    "acetic acid methyl ester": "COC(C)=O",
    "ethyl acetate": "CCOC(C)=O",
    "etoac": "CCOC(C)=O",
    "ea": "CCOC(C)=O",
    "acoet": "CCOC(C)=O",
    "acetic acid ethyl ester": "CCOC(C)=O",
    "ethyl ethanoate": "CCOC(C)=O",
    "propyl acetate": "CCCOC(C)=O",
    "n-propyl acetate": "CCCOC(C)=O",
    "acetic acid propyl ester": "CCCOC(C)=O",
    "isopropyl acetate": "CC(=O)OC(C)C",
    "ipac": "CC(=O)OC(C)C",
    "i-proac": "CC(=O)OC(C)C",
    "2-propyl acetate": "CC(=O)OC(C)C",
    "butyl acetate": "CCCCOC(C)=O",
    "n-butyl acetate": "CCCCOC(C)=O",
    "buoac": "CCCCOC(C)=O",
    "acetic acid butyl ester": "CCCCOC(C)=O",
    "isobutyl acetate": "CC(=O)OCC(C)C",
    "2-methylpropyl acetate": "CC(=O)OCC(C)C",
    "t-butyl acetate": "CC(=O)OC(C)(C)C",
    "tert-butyl acetate": "CC(=O)OC(C)(C)C",
    "amyl acetate": "CCCCCOC(C)=O",
    "n-amyl acetate": "CCCCCOC(C)=O",
    "pentyl acetate": "CCCCCOC(C)=O",
    "n-pentyl acetate": "CCCCCOC(C)=O",
    "isoamyl acetate": "CC(=O)OCCC(C)C",
    "isopentyl acetate": "CC(=O)OCCC(C)C",
    "3-methylbutyl acetate": "CC(=O)OCCC(C)C",
    "banana oil": "CC(=O)OCCC(C)C",
    "n-octyl acetate": "CCCCCCCCOC(C)=O",
    "octyl acetate": "CCCCCCCCOC(C)=O",
    "2-ethylhexyl acetate": "CCCCC(CC)COC(C)=O",
    "glycerol triacetate": "CC(=O)OCC(COC(C)=O)OC(C)=O",
    "triacetin": "CC(=O)OCC(COC(C)=O)OC(C)=O",
    "glyceryl triacetate": "CC(=O)OCC(COC(C)=O)OC(C)=O",
    "glycerol diacetate": "CC(=O)OCC(CO)OC(C)=O",
    "diacetin": "CC(=O)OCC(CO)OC(C)=O",

    # ===== ESTERS - FORMATES =====
    "methyl formate": "COC=O",
    "formic acid methyl ester": "COC=O",
    "ethyl formate": "CCOC=O",
    "formic acid ethyl ester": "CCOC=O",

    # ===== ESTERS - PROPIONATES =====
    "methyl propionate": "CCC(=O)OC",
    "propionic acid methyl ester": "CCC(=O)OC",
    "ethyl propionate": "CCOC(=O)CC",
    "propionic acid ethyl ester": "CCOC(=O)CC",

    # ===== ESTERS - LACTATES =====
    "methyl lactate": "COC(=O)C(C)O",
    "lactic acid methyl ester": "COC(=O)C(C)O",
    "methyl 2-hydroxypropanoate": "COC(=O)C(C)O",
    "ethyl lactate": "CCOC(=O)C(C)O",
    "lactic acid ethyl ester": "CCOC(=O)C(C)O",
    "ethyl 2-hydroxypropanoate": "CCOC(=O)C(C)O",

    # ===== ESTERS - DIESTERS =====
    "dimethyl succinate": "COC(=O)CCC(=O)OC",
    "succinic acid dimethyl ester": "COC(=O)CCC(=O)OC",
    "diethyl succinate": "CCOC(=O)CCC(=O)OCC",
    "succinic acid diethyl ester": "CCOC(=O)CCC(=O)OCC",
    "dimethyl adipate": "COC(=O)CCCCC(=O)OC",
    "adipic acid dimethyl ester": "COC(=O)CCCCC(=O)OC",
    "methyl oleate": "CCCCCCCC/C=C\\CCCCCCCC(=O)OC",
    "oleic acid methyl ester": "CCCCCCCC/C=C\\CCCCCCCC(=O)OC",

    # ===== ESTERS - CARBONATES =====
    "dimethyl carbonate": "COC(=O)OC",
    "dmc": "COC(=O)OC",
    "carbonic acid dimethyl ester": "COC(=O)OC",
    "diethyl carbonate": "CCOC(=O)OCC",
    "dec": "CCOC(=O)OCC",
    "carbonic acid diethyl ester": "CCOC(=O)OCC",
    "ethylene carbonate": "O=C1OCCO1",
    "1,3-dioxolan-2-one": "O=C1OCCO1",
    "ec": "O=C1OCCO1",
    "propylene carbonate": "CC1COC(=O)O1",
    "1,2-propylene carbonate": "CC1COC(=O)O1",
    "pc": "CC1COC(=O)O1",
    "4-methyl-1,3-dioxolan-2-one": "CC1COC(=O)O1",
    "butylene carbonate": "CCC1COC(=O)O1",
    "1,2-butylene carbonate": "CCC1COC(=O)O1",

    # ===== LACTONES =====
    "gamma-valerolactone": "CC1CCC(=O)O1",
    "\u03b3-valerolactone": "CC1CCC(=O)O1",
    "gvl": "CC1CCC(=O)O1",
    "5-methyloxolan-2-one": "CC1CCC(=O)O1",

    # ===== KETONES =====
    "acetone": "CC(C)=O",
    "propan-2-one": "CC(C)=O",
    "propanone": "CC(C)=O",
    "dimethyl ketone": "CC(C)=O",
    "methylethyl ketone": "CCC(C)=O",
    "methyl ethyl ketone": "CCC(C)=O",
    "mek": "CCC(C)=O",
    "2-butanone": "CCC(C)=O",
    "butan-2-one": "CCC(C)=O",
    "ethyl methyl ketone": "CCC(C)=O",
    "2-pentanone": "CCCC(C)=O",
    "pentan-2-one": "CCCC(C)=O",
    "methyl propyl ketone": "CCCC(C)=O",
    "mpk": "CCCC(C)=O",
    "3-pentanone": "CCC(=O)CC",
    "pentan-3-one": "CCC(=O)CC",
    "diethyl ketone": "CCC(=O)CC",
    "dek": "CCC(=O)CC",
    "methylisobutyl ketone": "CC(=O)CC(C)C",
    "methyl isobutyl ketone": "CC(=O)CC(C)C",
    "mibk": "CC(=O)CC(C)C",
    "4-methylpentan-2-one": "CC(=O)CC(C)C",
    "4-methyl-2-pentanone": "CC(=O)CC(C)C",
    "isopropylacetone": "CC(=O)CC(C)C",
    "cyclopentanone": "O=C1CCCC1",
    "cyclohexanone": "O=C1CCCCC1",
    "pimelic ketone": "O=C1CCCCC1",

    # ===== AROMATICS - HYDROCARBONS =====
    "benzene": "c1ccccc1",
    "phh": "c1ccccc1",
    "c6h6": "c1ccccc1",
    "toluene": "Cc1ccccc1",
    "phme": "Cc1ccccc1",
    "methylbenzene": "Cc1ccccc1",
    "tol": "Cc1ccccc1",
    "phenylmethane": "Cc1ccccc1",
    "p-xylene": "Cc1ccc(C)cc1",
    "para-xylene": "Cc1ccc(C)cc1",
    "1,4-dimethylbenzene": "Cc1ccc(C)cc1",
    "1,4-xylene": "Cc1ccc(C)cc1",
    "xylene": "Cc1ccccc1C",
    "xylenes": "Cc1ccccc1C",
    "o-xylene": "Cc1ccccc1C",
    "ortho-xylene": "Cc1ccccc1C",
    "1,2-dimethylbenzene": "Cc1ccccc1C",
    "m-xylene": "Cc1cccc(C)c1",
    "meta-xylene": "Cc1cccc(C)c1",
    "mesitylene": "Cc1cc(C)cc(C)c1",
    "1,3,5-trimethylbenzene": "Cc1cc(C)cc(C)c1",
    "cumene": "CC(C)c1ccccc1",
    "isopropylbenzene": "CC(C)c1ccccc1",
    "(1-methylethyl)benzene": "CC(C)c1ccccc1",
    "p-cymene": "Cc1ccc(C(C)C)cc1",
    "para-cymene": "Cc1ccc(C(C)C)cc1",
    "4-isopropyltoluene": "Cc1ccc(C(C)C)cc1",
    "1-methyl-4-isopropylbenzene": "Cc1ccc(C(C)C)cc1",

    # ===== AROMATICS - ETHERS =====
    "anisole": "COc1ccccc1",
    "methoxybenzene": "COc1ccccc1",
    "phenyl methyl ether": "COc1ccccc1",
    "ethoxybenzene": "CCOc1ccccc1",
    "phenetole": "CCOc1ccccc1",
    "phenyl ethyl ether": "CCOc1ccccc1",
    "diphenyl ether": "c1ccc(Oc2ccccc2)cc1",
    "diphenylether": "c1ccc(Oc2ccccc2)cc1",
    "phenyl ether": "c1ccc(Oc2ccccc2)cc1",
    "phenoxybenzene": "c1ccc(Oc2ccccc2)cc1",

    # ===== AROMATICS - HALOGENATED =====
    "chlorobenzene": "Clc1ccccc1",
    "phcl": "Clc1ccccc1",
    "monochlorobenzene": "Clc1ccccc1",
    "mcb": "Clc1ccccc1",
    "1,2-dichlorobenzene": "Clc1ccccc1Cl",
    "o-dichlorobenzene": "Clc1ccccc1Cl",
    "odcb": "Clc1ccccc1Cl",
    "ortho-dichlorobenzene": "Clc1ccccc1Cl",
    "1,2,4-trichlorobenzene": "Clc1ccc(Cl)c(Cl)c1",
    "tcb": "Clc1ccc(Cl)c(Cl)c1",
    "fluorobenzene": "Fc1ccccc1",
    "phf": "Fc1ccccc1",
    "monofluorobenzene": "Fc1ccccc1",
    "trifluorotoluene": "FC(F)(F)c1ccccc1",
    "benzotrifluoride": "FC(F)(F)c1ccccc1",
    "btf": "FC(F)(F)c1ccccc1",
    "\u03b1,\u03b1,\u03b1-trifluorotoluene": "FC(F)(F)c1ccccc1",
    "(trifluoromethyl)benzene": "FC(F)(F)c1ccccc1",
    "perfluorotoluene": "Fc1c(F)c(F)c(C(F)(F)F)c(F)c1F",
    "hexafluorotoluene": "Fc1c(F)c(F)c(C(F)(F)F)c(F)c1F",

    # ===== AROMATICS - NITROGEN =====
    "pyridine": "c1ccncc1",
    "py": "c1ccncc1",
    "azabenzene": "c1ccncc1",
    "azine": "c1ccncc1",
    "2,4,6-collidine": "Cc1cc(C)nc(C)c1",
    "collidine": "Cc1cc(C)nc(C)c1",
    "2,4,6-trimethylpyridine": "Cc1cc(C)nc(C)c1",
    "sym-collidine": "Cc1cc(C)nc(C)c1",
    "n,n-dimethylaniline": "CN(C)c1ccccc1",
    "dimethylaniline": "CN(C)c1ccccc1",
    "dma": "CN(C)c1ccccc1",

    # ===== ALIPHATIC HYDROCARBONS =====
    "pentane": "CCCCC",
    "n-pentane": "CCCCC",
    "c5h12": "CCCCC",
    "2-methylpentane": "CCCC(C)C",
    "isohexane": "CCCC(C)C",
    "hexane": "CCCCCC",
    "n-hexane": "CCCCCC",
    "hexanes": "CCCCCC",
    "c6h14": "CCCCCC",
    "heptane": "CCCCCCC",
    "n-heptane": "CCCCCCC",
    "heptanes": "CCCCCCC",
    "c7h16": "CCCCCCC",
    "isooctane": "CC(C)CC(C)(C)C",
    "2,2,4-trimethylpentane": "CC(C)CC(C)(C)C",
    "iso-octane": "CC(C)CC(C)(C)C",
    "cyclohexane": "C1CCCCC1",
    "chex": "C1CCCCC1",
    "c-hex": "C1CCCCC1",
    "hexahydrobenzene": "C1CCCCC1",
    "c6h12": "C1CCCCC1",
    "methylcyclohexane": "CC1CCCCC1",
    "methyl cyclohexane": "CC1CCCCC1",
    "hexahydrotoluene": "CC1CCCCC1",
    "methylcyclopentane": "CC1CCCC1",
    "methyl cyclopentane": "CC1CCCC1",
    "cis-decalin": "C1CCC2CCCCC2C1",
    "decalin": "C1CCC2CCCCC2C1",
    "decahydronaphthalene": "C1CCC2CCCCC2C1",
    "bicyclo[4.4.0]decane": "C1CCC2CCCCC2C1",
    "petroleum ether": "CCCCCC",
    "pet ether": "CCCCCC",
    "petrol ether": "CCCCCC",
    "ligroin": "CCCCCC",
    "pet. ether": "CCCCCC",
    "light petroleum": "CCCCCC",

    # ===== TERPENES =====
    "d-limonene": "C=C(C)[C@H]1CC=C(C)CC1",
    "(r)-limonene": "C=C(C)[C@H]1CC=C(C)CC1",
    "(+)-limonene": "C=C(C)[C@H]1CC=C(C)CC1",
    "l-limonene": "C=C(C)[C@@H]1CC=C(C)CC1",
    "(s)-limonene": "C=C(C)[C@@H]1CC=C(C)CC1",
    "(-)-limonene": "C=C(C)[C@@H]1CC=C(C)CC1",
    "limonene": "C=C(C)[C@H]1CC=C(C)CC1",
    "dipentene": "C=C(C)[C@H]1CC=C(C)CC1",

    # ===== ETHERS - CYCLIC =====
    "tetrahydrofuran": "C1CCOC1",
    "thf": "C1CCOC1",
    "oxolane": "C1CCOC1",
    "tetramethylene oxide": "C1CCOC1",
    "2-methyltetrahydrofuran": "CC1CCCO1",
    "2-me-thf": "CC1CCCO1",
    "2-methf": "CC1CCCO1",
    "me-thf": "CC1CCCO1",
    "methf": "CC1CCCO1",
    "2-mthf": "CC1CCCO1",
    "mthf": "CC1CCCO1",
    "2-methyloxolane": "CC1CCCO1",
    "1,4-dioxane": "C1COCCO1",
    "dioxane": "C1COCCO1",
    "p-dioxane": "C1COCCO1",
    "diethylene dioxide": "C1COCCO1",
    "1,3-dioxolane": "C1COCO1",
    "dioxolane": "C1COCO1",
    "formal glycol": "C1COCO1",

    # ===== ETHERS - ACYCLIC =====
    "dimethyl ether": "COC",
    "methoxymethane": "COC",
    "wood ether": "COC",
    "diethyl ether": "CCOCC",
    "et2o": "CCOCC",
    "ether": "CCOCC",
    "ethoxyethane": "CCOCC",
    "ethyl ether": "CCOCC",
    "diethylether": "CCOCC",
    "sulfuric ether": "CCOCC",
    "diisopropyl ether": "CC(C)OC(C)C",
    "dipe": "CC(C)OC(C)C",
    "ipe": "CC(C)OC(C)C",
    "isopropyl ether": "CC(C)OC(C)C",
    "dibutyl ether": "CCCCOCCCC",
    "butyl ether": "CCCCOCCCC",
    "di-n-butyl ether": "CCCCOCCCC",
    "t-butylmethyl ether": "COC(C)(C)C",
    "tert-butyl methyl ether": "COC(C)(C)C",
    "mtbe": "COC(C)(C)C",
    "methyl tert-butyl ether": "COC(C)(C)C",
    "tbme": "COC(C)(C)C",
    "methyl t-butyl ether": "COC(C)(C)C",
    "t-butyl ethyl ether": "CCOC(C)(C)C",
    "tert-butyl ethyl ether": "CCOC(C)(C)C",
    "etbe": "CCOC(C)(C)C",
    "ethyl tert-butyl ether": "CCOC(C)(C)C",
    "t-amyl methyl ether": "CCC(C)(C)OC",
    "tert-amyl methyl ether": "CCC(C)(C)OC",
    "tame": "CCC(C)(C)OC",
    "methyl tert-amyl ether": "CCC(C)(C)OC",
    "cyclopentyl methyl ether": "COC1CCCC1",
    "cpme": "COC1CCCC1",
    "methyl cyclopentyl ether": "COC1CCCC1",

    # ===== ETHERS - GLYMES =====
    "1,2-dimethoxyethane": "COCCOC",
    "dimethoxyethane": "COCCOC",
    "glyme": "COCCOC",
    "monoglyme": "COCCOC",
    "dme": "COCCOC",
    "ethylene glycol dimethyl ether": "COCCOC",
    "egdme": "COCCOC",
    "bis(2-methoxyethyl) ether": "COCCOCCOC",
    "diglyme": "COCCOCCOC",
    "diethylene glycol dimethyl ether": "COCCOCCOC",
    "degdme": "COCCOCCOC",
    "triglyme": "COCCOCCOCCOC",
    "triethylene glycol dimethyl ether": "COCCOCCOCCOC",
    "dimethoxymethane": "COCOC",
    "methylal": "COCOC",
    "formal": "COCOC",
    "diethoxymethane": "CCOCOCC",
    "ethylal": "CCOCOCC",
    "diethylene glycol monobutyl ether": "CCCCOCCOCCO",
    "butyl carbitol": "CCCCOCCOCCO",
    "degbe": "CCCCOCCOCCO",
    "2-(2-butoxyethoxy)ethanol": "CCCCOCCOCCO",
    "1,2,3-trimethoxypropane": "COCC(COC)OC",
    "trimethoxypropane": "COCC(COC)OC",
    "dimethyl isosorbide": "CO[C@H]1CO[C@H]2[C@@H]1OC[C@H]2OC",
    "dmi": "CO[C@H]1CO[C@H]2[C@@H]1OC[C@H]2OC",

    # ===== POLAR APROTIC - AMIDES =====
    "formamide": "NC=O",
    "methanamide": "NC=O",
    "n-methylformamide": "CNC=O",
    "nmf": "CNC=O",
    "monomethylformamide": "CNC=O",
    "dimethyl formamide": "CN(C)C=O",
    "dimethylformamide": "CN(C)C=O",
    "dmf": "CN(C)C=O",
    "n,n-dimethylformamide": "CN(C)C=O",
    "dimethylforamide": "CN(C)C=O",
    "dimethyl acetamide": "CC(=O)N(C)C",
    "dimethylacetamide": "CC(=O)N(C)C",
    "dimethylacetimide": "CC(=O)N(C)C",
    "dmac": "CC(=O)N(C)C",
    "n,n-dimethylacetamide": "CC(=O)N(C)C",
    "dmaac": "CC(=O)N(C)C",
    "n-methyl pyrrolidone": "CN1CCCC1=O",
    "n-methylpyrrolidone": "CN1CCCC1=O",
    "nmp": "CN1CCCC1=O",
    "n-methyl-2-pyrrolidone": "CN1CCCC1=O",
    "1-methyl-2-pyrrolidone": "CN1CCCC1=O",
    "m-pyrol": "CN1CCCC1=O",
    "n-ethylpyrrolidone": "CCN1CCCC1=O",
    "nep": "CCN1CCCC1=O",
    "n-ethyl-2-pyrrolidone": "CCN1CCCC1=O",
    "1-ethyl-2-pyrrolidone": "CCN1CCCC1=O",
    "n,n-dimethyloctanamide": "CCCCCCCC(=O)N(C)C",
    "dimethyloctanamide": "CCCCCCCC(=O)N(C)C",
    "n,n-dimethyldecanamide": "CCCCCCCCCC(=O)N(C)C",
    "dimethyldecanamide": "CCCCCCCCCC(=O)N(C)C",

    # ===== POLAR APROTIC - UREAS =====
    "tetramethylurea": "CN(C)C(=O)N(C)C",
    "tmu": "CN(C)C(=O)N(C)C",
    "1,3-dimethyl-2-imidazolidinone": "CN1CCN(C)C1=O",
    "dmeu": "CN1CCN(C)C1=O",
    "1,3-dimethylimidazolidin-2-one": "CN1CCN(C)C1=O",
    "dimethylpropylene urea": "CN1CCCN(C)C1=O",
    "dmpu": "CN1CCCN(C)C1=O",
    "1,3-dimethyl-3,4,5,6-tetrahydro-2(1h)-pyrimidinone": "CN1CCCN(C)C1=O",

    # ===== POLAR APROTIC - SULFUR =====
    "dimethyl sulfoxide": "CS(C)=O",
    "dmso": "CS(C)=O",
    "methylsulfinylmethane": "CS(C)=O",
    "methyl sulfoxide": "CS(C)=O",
    "sulfolane": "O=S1(=O)CCCC1",
    "tetramethylene sulfone": "O=S1(=O)CCCC1",
    "tetrahydrothiophene 1,1-dioxide": "O=S1(=O)CCCC1",
    "carbon disulfide": "S=C=S",
    "cs2": "S=C=S",
    "carbon bisulfide": "S=C=S",

    # ===== POLAR APROTIC - NITRILES =====
    "acetonitrile": "CC#N",
    "mecn": "CC#N",
    "acn": "CC#N",
    "ch3cn": "CC#N",
    "methyl cyanide": "CC#N",
    "cyanomethane": "CC#N",
    "ethanenitrile": "CC#N",
    "propanenitrile": "CCC#N",
    "propionitrile": "CCC#N",
    "etcn": "CCC#N",
    "ethyl cyanide": "CCC#N",
    "trichloroacetonitrile": "N#CC(Cl)(Cl)Cl",

    # ===== HALOGENATED - ALIPHATIC =====
    "dichloromethane": "ClCCl",
    "dcm": "ClCCl",
    "methylene chloride": "ClCCl",
    "ch2cl2": "ClCCl",
    "methylene dichloride": "ClCCl",
    "chloroform": "ClC(Cl)Cl",
    "chcl3": "ClC(Cl)Cl",
    "trichloromethane": "ClC(Cl)Cl",
    "methyl trichloride": "ClC(Cl)Cl",
    "carbon tetrachloride": "ClC(Cl)(Cl)Cl",
    "ccl4": "ClC(Cl)(Cl)Cl",
    "tetrachloromethane": "ClC(Cl)(Cl)Cl",
    "carbon tet": "ClC(Cl)(Cl)Cl",
    "1,2-dichloroethane": "ClCCCl",
    "dce": "ClCCCl",
    "ethylene dichloride": "ClCCCl",
    "edc": "ClCCCl",

    # ===== HALOGENATED - PERFLUORINATED =====
    "perfluorohexane": "FC(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F",
    "c6f14": "FC(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F",
    "perfluorocyclohexane": "FC1(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C1(F)F",

    # ===== MISCELLANEOUS =====
    "nitromethane": "C[N+](=O)[O-]",
    "meno2": "C[N+](=O)[O-]",
    "ch3no2": "C[N+](=O)[O-]",
    "triethylamine": "CCN(CC)CC",
    "tea": "CCN(CC)CC",
    "et3n": "CCN(CC)CC",
    "net3": "CCN(CC)CC",
    "n,n-diethylethanamine": "CCN(CC)CC",
    "acetic anhydride": "CC(=O)OC(C)=O",
    "ac2o": "CC(=O)OC(C)=O",
    "ethanoic anhydride": "CC(=O)OC(C)=O",
    "acetyl anhydride": "CC(=O)OC(C)=O",
    "furfural": "O=Cc1ccco1",
    "2-furaldehyde": "O=Cc1ccco1",
    "furan-2-carbaldehyde": "O=Cc1ccco1",
    "furfuraldehyde": "O=Cc1ccco1",
    "dihydrolevoglucosenone": "O=C1CC[C@H]2CO[C@@H]1O2",
    "cyrene": "O=C1CC[C@H]2CO[C@@H]1O2",

    # ===== BASES (sometimes used as solvent) =====
    "diisopropylethylamine": "CCN(C(C)C)C(C)C",
    "dipea": "CCN(C(C)C)C(C)C",
    "diea": "CCN(C(C)C)C(C)C",
    "hunig's base": "CCN(C(C)C)C(C)C",
    "hunigs base": "CCN(C(C)C)C(C)C",
    "n,n-diisopropylethylamine": "CCN(C(C)C)C(C)C",
}

DEUTERATED_SOLVENTS = {
    "cdcl3": "[2H]C(Cl)(Cl)Cl",
    "chloroform-d": "[2H]C(Cl)(Cl)Cl",
    "deuterated chloroform": "[2H]C(Cl)(Cl)Cl",
    "deuterochloroform": "[2H]C(Cl)(Cl)Cl",
    "dcl3": "[2H]C(Cl)(Cl)Cl",
    "dmso-d6": "[2H]C([2H])([2H])S(=O)C([2H])([2H])[2H]",
    "d6-dmso": "[2H]C([2H])([2H])S(=O)C([2H])([2H])[2H]",
    "(cd3)2so": "[2H]C([2H])([2H])S(=O)C([2H])([2H])[2H]",
    "dmso d6": "[2H]C([2H])([2H])S(=O)C([2H])([2H])[2H]",
    "cd3od": "[2H]C([2H])([2H])O[2H]",
    "methanol-d4": "[2H]C([2H])([2H])O[2H]",
    "meod": "[2H]C([2H])([2H])O[2H]",
    "meod-d4": "[2H]C([2H])([2H])O[2H]",
    "methanol d4": "[2H]C([2H])([2H])O[2H]",
    "acetone-d6": "[2H]C([2H])([2H])C(=O)C([2H])([2H])[2H]",
    "(cd3)2co": "[2H]C([2H])([2H])C(=O)C([2H])([2H])[2H]",
    "acetone d6": "[2H]C([2H])([2H])C(=O)C([2H])([2H])[2H]",
    "c6d6": "[2H]c1c([2H])c([2H])c([2H])c([2H])c1[2H]",
    "benzene-d6": "[2H]c1c([2H])c([2H])c([2H])c([2H])c1[2H]",
    "benzene d6": "[2H]c1c([2H])c([2H])c([2H])c([2H])c1[2H]",
    "d2o": "[2H]O[2H]",
    "deuterium oxide": "[2H]O[2H]",
    "heavy water": "[2H]O[2H]",
    "cd3cn": "[2H]C([2H])([2H])C#N",
    "acetonitrile-d3": "[2H]C([2H])([2H])C#N",
    "mecn-d3": "[2H]C([2H])([2H])C#N",
    "thf-d8": "[2H]C1([2H])OC([2H])([2H])C([2H])([2H])C1([2H])[2H]",
    "thf d8": "[2H]C1([2H])OC([2H])([2H])C([2H])([2H])C1([2H])[2H]",
    "toluene-d8": "[2H]C([2H])([2H])c1c([2H])c([2H])c([2H])c([2H])c1[2H]",
    "toluene d8": "[2H]C([2H])([2H])c1c([2H])c([2H])c([2H])c([2H])c1[2H]",
    "cd2cl2": "[2H]C([2H])(Cl)Cl",
    "dcm-d2": "[2H]C([2H])(Cl)Cl",
    "dichloromethane-d2": "[2H]C([2H])(Cl)Cl",
    "pyridine-d5": "[2H]c1c([2H])c([2H])nc([2H])c1[2H]",
    "pyridine d5": "[2H]c1c([2H])c([2H])nc([2H])c1[2H]",
    "dmf-d7": "[2H]C([2H])([2H])N(C([2H])([2H])[2H])C(=O)[2H]",
    "dmf d7": "[2H]C([2H])([2H])N(C([2H])([2H])[2H])C(=O)[2H]",
    "dioxane-d8": "[2H]C1([2H])OC([2H])([2H])C([2H])([2H])OC1([2H])[2H]",
    "dioxane d8": "[2H]C1([2H])OC([2H])([2H])C([2H])([2H])OC1([2H])[2H]",
}
